### ISSUE TITLE
Playing song from a remote url

### ISSUE THREAD

**Issue by snowjuan** [tbaranes/AudioPlayerSwift#10]
cannot load url file, Sound initialization failed

please test and give solution, thanks.

**Comment by tbaranes** [comment]
What are you talking about? The demo app? Your own project?

**Comment by snowjuan** [comment]
Hi, sorry to confuse you. 
I tried run the demo on iOS 10 device, it works until I upload 'sound1.caf' to drop box and try to initialize Audio player with URL:
sound1 = try AudioPlayer(contentsOf: URL(string: "https://dl.dropboxusercontent.com/s/huop20175jevr36/sound1.caf")!)

there is no sound when click both of the two play buttons after install on device. And there is an error 'Sound initialization failed' in the debug window.

Hope this is understandable, thanks.

**Comment by tbaranes** [comment]
Oh, I got it! Thanks for the details.

`AudioPlayerSwift` doesn't handle _real_ url, but just local files. So, you have to first download your files, then you can use this initialiser with an url from `FileManager`. 

If you really want to add this feature, PRs are welcome 🙃

**Comment by snowjuan** [comment]
Compare the difference between AVPlayer and AVAudioPlayer which was used in AudioPlayerSwift, AVPlayer seems provider the way to init with both remote url and local path, I will code with it. Thanks.
