### ISSUE TITLE
None of your accounts are a member of 'TNVENL2JX3' error

### ISSUE THREAD

**Issue by frranck** [tbaranes/AudioPlayerSwift#13]
Hi,
Could you set "team" to none inside the General/Signing section of the settings in the AudioPlayerSwift.xcodeproj you ship ?
I need to do it manually after updating carthage, otherwise when trying to build my project, i'm getting this error:
"None of your accounts are a member of 'TNVENL2JX3':  An unexpected error occurred. Xcode cannot find a team matching 'TNVENL2JX3'."

**Comment by tbaranes** [comment]
Just pushed a fix on master, can you give it a second try?

**Comment by frranck** [comment]
@tbaranes Thanks Tom, it is fixed.
BTW did you try to test the fadein/out in the unit tests ? I tried to add some tests but it seems the Timer.scheduledTimer thing doesn't work there.

**Comment by tbaranes** [comment]
There's no tests in AudioPlayerSwift, that's definitely missing. If you write some, don't hesitate to send a PR 👯 

Not sure about your question, what is not working? The timer or the fade?

**Comment by frranck** [comment]
Testing the fadings is failing for me (I guess because of the timers), audio don't even get considered as stopped.

**Comment by tbaranes** [comment]
Not sure why that's happening, I don't have time to investigate right now, but you can open another issue until we find a solution.

I'm gonna close this one it's fixed.
