### ISSUE TITLE
Song is silent in iOS 10

### ISSUE THREAD

**Issue by bungkhus** [tbaranes/AudioPlayerSwift#22]
Hi,
I use this library in iOS 11 (simulator) and work well. But, when i use in my iOS 10 real device, the song is silent. why is this happening? is it because ios version?
Thank

**Comment by tbaranes** [comment]
Is it working on iOS 10 simulator? Are you sure that your iPhone is not in silent mode? Are you reproducing using the example app?

**Comment by tbaranes** [comment]
Closing now, don't hesitate to reopen if you still have an issue.
