### ISSUE TITLE
Compile error on swift 4

### ISSUE THREAD

**Issue by marlon-sousa** [tbaranes/AudioPlayerSwift#24]
Hello,

I have used successfully this library but had to make a small change in order to compile it for swift v 4.

I am using xcode 9,1 here and the default configurations for a swift project.

On compiling, xcode complained that the HandleFadeTo function (line 86 currently) was not able to get seen by objective c and asked to include an @objc directive before it.

I did exactly that and then the compile went smoothly.

I wanted to submit a pool request but git specially on github is still confusing enough that I would not risk playing with branches on a public project, not yet at least. But here it is if you want to patch it yourself or for other people who happen to have the same issue.

**Comment by tbaranes** [comment]
Thanks for the report! Swift 4 is already supported since last August, but I just saw that the CocoaPods version is outdated. So, I suppose you are installing the library using that dependency manager? 

I will upload the last version to CocoaPods this week, thanks again for reporting this!

**Comment by tbaranes** [comment]
Finally made the CocoaPods release! I don't know why but the 1.6.0 was failing, but duplicating it and releasing a 1.6.1 (no diff) passed. Anyway, sorry for the delay, starting now `AudioPlayerSwift` is fully supporting Swift 4 using CocoaPods!
