### ISSUE TITLE
the demo can't play online sounds 

### ISSUE THREAD

**Issue by a1259667899** [tbaranes/AudioPlayerSwift#25]

**Comment by tbaranes** [comment]
Just tried, it's working as expected. Could you give it a second try?

**Comment by a1259667899** [comment]
I  do this :
` sound1 = try AudioPlayer.init(contentsOf: URL.init(string: "http://www.tingge123.com/mp3/2016-04-09/1460169765.mp3")!)`

**Comment by tbaranes** [comment]
`AudioPlayerSwift` supports only local files, not remote. You have to download it yourself before playing it.
