### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [tbaranes/AudioPlayerSwift#26]
Hi @tbaranes . I'm graphic disigner. I would like to know if you are interested that I make a logo for your project? If you allowed me, i"ll make logo for your project and it's free.
Best Regard

**Comment by tbaranes** [comment]
Sure, you can go ahead! A logo is always nice to have 👍

**Comment by mirzazulfan** [comment]
Thanks for your response @tbaranes . . I've Designed a logo for your project, tell me if you need some change i'll fix it and if you have an idea please share with me, it would be better for me.
![v 1](https://user-images.githubusercontent.com/36124339/41984124-18785452-7a5a-11e8-8c99-8d2cb49784d5.png)

**Comment by tbaranes** [comment]
The first one is cool, simple 👍 
Do you mind to make a PR to add this to the README?

**Comment by mirzazulfan** [comment]
Hi @tbaranes . I'm glad you liked it. you can download all files [here](https://drive.google.com/drive/folders/1iivEmCLG6oIOJ7T4hypC1TLbYvXFbzGj?ogsrc=32) . I've created a pr #27 Please check. Thank you

**Comment by tbaranes** [comment]
Closed by #27
